// flow-typed signature: 59cb1425f0b580a9f018b5f6553cb8de
// flow-typed version: <<STUB>>/slate_v^0.14.15/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate/dist/slate' {
  declare module.exports: any;
}

declare module 'slate/dist/slate.min' {
  declare module.exports: any;
}

declare module 'slate/lib/components/content' {
  declare module.exports: any;
}

declare module 'slate/lib/components/editor' {
  declare module.exports: any;
}

declare module 'slate/lib/components/leaf' {
  declare module.exports: any;
}

declare module 'slate/lib/components/node' {
  declare module.exports: any;
}

declare module 'slate/lib/components/placeholder' {
  declare module.exports: any;
}

declare module 'slate/lib/components/void' {
  declare module.exports: any;
}

declare module 'slate/lib/constants/environment' {
  declare module.exports: any;
}

declare module 'slate/lib/constants/types' {
  declare module.exports: any;
}

declare module 'slate/lib/index' {
  declare module.exports: any;
}

declare module 'slate/lib/models/block' {
  declare module.exports: any;
}

declare module 'slate/lib/models/character' {
  declare module.exports: any;
}

declare module 'slate/lib/models/data' {
  declare module.exports: any;
}

declare module 'slate/lib/models/document' {
  declare module.exports: any;
}

declare module 'slate/lib/models/inline' {
  declare module.exports: any;
}

declare module 'slate/lib/models/mark' {
  declare module.exports: any;
}

declare module 'slate/lib/models/node' {
  declare module.exports: any;
}

declare module 'slate/lib/models/schema' {
  declare module.exports: any;
}

declare module 'slate/lib/models/selection' {
  declare module.exports: any;
}

declare module 'slate/lib/models/state' {
  declare module.exports: any;
}

declare module 'slate/lib/models/text' {
  declare module.exports: any;
}

declare module 'slate/lib/models/transform' {
  declare module.exports: any;
}

declare module 'slate/lib/plugins/core' {
  declare module.exports: any;
}

declare module 'slate/lib/serializers/base-64' {
  declare module.exports: any;
}

declare module 'slate/lib/serializers/html' {
  declare module.exports: any;
}

declare module 'slate/lib/serializers/plain' {
  declare module.exports: any;
}

declare module 'slate/lib/serializers/raw' {
  declare module.exports: any;
}

declare module 'slate/lib/transforms/apply-operation' {
  declare module.exports: any;
}

declare module 'slate/lib/transforms/at-current-range' {
  declare module.exports: any;
}

declare module 'slate/lib/transforms/at-range' {
  declare module.exports: any;
}

declare module 'slate/lib/transforms/by-key' {
  declare module.exports: any;
}

declare module 'slate/lib/transforms/index' {
  declare module.exports: any;
}

declare module 'slate/lib/transforms/normalize' {
  declare module.exports: any;
}

declare module 'slate/lib/transforms/on-history' {
  declare module.exports: any;
}

declare module 'slate/lib/transforms/on-selection' {
  declare module.exports: any;
}

declare module 'slate/lib/transforms/operations' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/find-dom-node' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/is-in-range' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/is-react-component' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/memoize' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/normalize' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/offset-key' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/scroll-to' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/string' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/transfer' {
  declare module.exports: any;
}

declare module 'slate/lib/utils/uid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate/dist/slate.js' {
  declare module.exports: $Exports<'slate/dist/slate'>;
}
declare module 'slate/dist/slate.min.js' {
  declare module.exports: $Exports<'slate/dist/slate.min'>;
}
declare module 'slate/lib/components/content.js' {
  declare module.exports: $Exports<'slate/lib/components/content'>;
}
declare module 'slate/lib/components/editor.js' {
  declare module.exports: $Exports<'slate/lib/components/editor'>;
}
declare module 'slate/lib/components/leaf.js' {
  declare module.exports: $Exports<'slate/lib/components/leaf'>;
}
declare module 'slate/lib/components/node.js' {
  declare module.exports: $Exports<'slate/lib/components/node'>;
}
declare module 'slate/lib/components/placeholder.js' {
  declare module.exports: $Exports<'slate/lib/components/placeholder'>;
}
declare module 'slate/lib/components/void.js' {
  declare module.exports: $Exports<'slate/lib/components/void'>;
}
declare module 'slate/lib/constants/environment.js' {
  declare module.exports: $Exports<'slate/lib/constants/environment'>;
}
declare module 'slate/lib/constants/types.js' {
  declare module.exports: $Exports<'slate/lib/constants/types'>;
}
declare module 'slate/lib/index.js' {
  declare module.exports: $Exports<'slate/lib/index'>;
}
declare module 'slate/lib/models/block.js' {
  declare module.exports: $Exports<'slate/lib/models/block'>;
}
declare module 'slate/lib/models/character.js' {
  declare module.exports: $Exports<'slate/lib/models/character'>;
}
declare module 'slate/lib/models/data.js' {
  declare module.exports: $Exports<'slate/lib/models/data'>;
}
declare module 'slate/lib/models/document.js' {
  declare module.exports: $Exports<'slate/lib/models/document'>;
}
declare module 'slate/lib/models/inline.js' {
  declare module.exports: $Exports<'slate/lib/models/inline'>;
}
declare module 'slate/lib/models/mark.js' {
  declare module.exports: $Exports<'slate/lib/models/mark'>;
}
declare module 'slate/lib/models/node.js' {
  declare module.exports: $Exports<'slate/lib/models/node'>;
}
declare module 'slate/lib/models/schema.js' {
  declare module.exports: $Exports<'slate/lib/models/schema'>;
}
declare module 'slate/lib/models/selection.js' {
  declare module.exports: $Exports<'slate/lib/models/selection'>;
}
declare module 'slate/lib/models/state.js' {
  declare module.exports: $Exports<'slate/lib/models/state'>;
}
declare module 'slate/lib/models/text.js' {
  declare module.exports: $Exports<'slate/lib/models/text'>;
}
declare module 'slate/lib/models/transform.js' {
  declare module.exports: $Exports<'slate/lib/models/transform'>;
}
declare module 'slate/lib/plugins/core.js' {
  declare module.exports: $Exports<'slate/lib/plugins/core'>;
}
declare module 'slate/lib/serializers/base-64.js' {
  declare module.exports: $Exports<'slate/lib/serializers/base-64'>;
}
declare module 'slate/lib/serializers/html.js' {
  declare module.exports: $Exports<'slate/lib/serializers/html'>;
}
declare module 'slate/lib/serializers/plain.js' {
  declare module.exports: $Exports<'slate/lib/serializers/plain'>;
}
declare module 'slate/lib/serializers/raw.js' {
  declare module.exports: $Exports<'slate/lib/serializers/raw'>;
}
declare module 'slate/lib/transforms/apply-operation.js' {
  declare module.exports: $Exports<'slate/lib/transforms/apply-operation'>;
}
declare module 'slate/lib/transforms/at-current-range.js' {
  declare module.exports: $Exports<'slate/lib/transforms/at-current-range'>;
}
declare module 'slate/lib/transforms/at-range.js' {
  declare module.exports: $Exports<'slate/lib/transforms/at-range'>;
}
declare module 'slate/lib/transforms/by-key.js' {
  declare module.exports: $Exports<'slate/lib/transforms/by-key'>;
}
declare module 'slate/lib/transforms/index.js' {
  declare module.exports: $Exports<'slate/lib/transforms/index'>;
}
declare module 'slate/lib/transforms/normalize.js' {
  declare module.exports: $Exports<'slate/lib/transforms/normalize'>;
}
declare module 'slate/lib/transforms/on-history.js' {
  declare module.exports: $Exports<'slate/lib/transforms/on-history'>;
}
declare module 'slate/lib/transforms/on-selection.js' {
  declare module.exports: $Exports<'slate/lib/transforms/on-selection'>;
}
declare module 'slate/lib/transforms/operations.js' {
  declare module.exports: $Exports<'slate/lib/transforms/operations'>;
}
declare module 'slate/lib/utils/find-dom-node.js' {
  declare module.exports: $Exports<'slate/lib/utils/find-dom-node'>;
}
declare module 'slate/lib/utils/is-in-range.js' {
  declare module.exports: $Exports<'slate/lib/utils/is-in-range'>;
}
declare module 'slate/lib/utils/is-react-component.js' {
  declare module.exports: $Exports<'slate/lib/utils/is-react-component'>;
}
declare module 'slate/lib/utils/memoize.js' {
  declare module.exports: $Exports<'slate/lib/utils/memoize'>;
}
declare module 'slate/lib/utils/normalize.js' {
  declare module.exports: $Exports<'slate/lib/utils/normalize'>;
}
declare module 'slate/lib/utils/offset-key.js' {
  declare module.exports: $Exports<'slate/lib/utils/offset-key'>;
}
declare module 'slate/lib/utils/scroll-to.js' {
  declare module.exports: $Exports<'slate/lib/utils/scroll-to'>;
}
declare module 'slate/lib/utils/string.js' {
  declare module.exports: $Exports<'slate/lib/utils/string'>;
}
declare module 'slate/lib/utils/transfer.js' {
  declare module.exports: $Exports<'slate/lib/utils/transfer'>;
}
declare module 'slate/lib/utils/uid.js' {
  declare module.exports: $Exports<'slate/lib/utils/uid'>;
}
