// Generated by psc-bundle 0.8.5.0
var PS = {};
(function(exports) {
  /* global exports, console */
  "use strict";

  // module Control.Monad.Eff.Console

  exports.log = function (s) {
    return function () {
      console.log(s);
      return {};
    };
  };
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  // Generated by psc version 0.8.5.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff.Console"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Show = PS["Data.Show"];
  exports["log"] = $foreign.log;
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  // Generated by psc version 0.8.5.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Console = PS["Control.Monad.Eff.Console"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ring = PS["Data.Ring"];        
  var main = Control_Monad_Eff_Console.log("Hello sailor!");
  var gcd = function (__copy_n) {
      return function (__copy_m) {
          var n = __copy_n;
          var m = __copy_m;
          tco: while (true) {
              if (n === 0) {
                  return m;
              };
              if (m === 0) {
                  return n;
              };
              if (n > m) {
                  var __tco_n = n - m;
                  var __tco_m = m;
                  n = __tco_n;
                  m = __tco_m;
                  continue tco;
              };
              var __tco_n = m - n;
              var __tco_m = n;
              n = __tco_n;
              m = __tco_m;
              continue tco;
          };
      };
  };
  exports["main"] = main;
  exports["gcd"] = gcd;
})(PS["Main"] = PS["Main"] || {});
PS["Main"].main();
